services:
  - type: web
    name: money-manager
    env: docker
    plan: free

    dockerfilePath: Dockerfile

    healthCheckPath: /login

    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod

      # Enter these values during initial Blueprint setup, or in Environment for an existing service.
      - key: DATABASE_URL
        sync: false

      - key: DATABASE_USERNAME
        sync: false

      - key: DATABASE_PASSWORD
        sync: false
